name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    name: Build binaries and create GitHub Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
  os: [ubuntu-latest, macos-latest]
  steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build
        run: |
          make build

    - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
      name: built-${{ runner.os }}
          path: |
            graph_parser/hra_runner*
            graph_parser/hra_expander*
            graph_parser/hra_test3*
            graph_parser/hras_dot_files/index.json
          if-no-files-found: error

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Zip per-OS payloads
        run: |
          mkdir -p upload
          for dir in dist/*; do \
            OS=$(basename "$dir" | sed 's/^built-//'); \
            zip -j "upload/hra-tools-${OS}.zip" "$dir"/*; \
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/hra-tools-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
